version: '3.5'

services:
  postgresql:
    container_name: starling-pgsql
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=starling_studio
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

networks:
  default:
    name: starling-network
