name: Integration tests

on:
  pull_request:
    branches:
      - master

jobs:
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Ivy Cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{runner.os}}-sbt-${{hashFiles('**/build.sbt')}}
      - name: Coursier cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-cache-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-cache-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }}-
            ${{ runner.os }}-coursier-cache-${{ matrix.scala }}-
            ${{ runner.os }}-coursier-cache-
      - name: Integration tests
        run: sbt "project integration" test
